// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdxvxpgaoyrwjhuazkvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1keHZ4cGdhb3lyd2podWF6a3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTEzNjQsImV4cCI6MjA3Mjg4NzM2NH0.QytD4DuLLqBab8XVOTF7ZsMe-P9wt5IO7D8whgqSgSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});